# Generated by Django 5.1.15 on 2026-06-18 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.RemoveField(
            model_name='monthlycontribution',
            name='payment_card_holder',
        ),
        migrations.RemoveField(
            model_name='monthlycontribution',
            name='payment_card_number',
        ),
        migrations.RemoveField(
            model_name='monthlycontribution',
            name='payment_note',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
