# Generated by Django 5.1.15 on 2026-06-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycontribution',
            name='payment_card_holder',
            field=models.CharField(blank=True, max_length=120, verbose_name='Karta egasi'),
        ),
        migrations.AddField(
            model_name='monthlycontribution',
            name='payment_card_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Karta raqami'),
        ),
        migrations.AddField(
            model_name='monthlycontribution',
            name='payment_note',
            field=models.TextField(blank=True, verbose_name="To'lov izohi"),
        ),
    ]
