# Generated by Django 5.1.15 on 2026-06-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_monthlycontribution_payment_card_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlycontribution',
            name='payment_note',
        ),
    ]
