# Generated by Django 5.1.15 on 2026-06-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_remove_monthlycontribution_payment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
