# Generated by Django 5.1.15 on 2026-06-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_payment_receipt_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.FileField(blank=True, upload_to='receipts/'),
        ),
    ]
