# Generated by Django 5.1.15 on 2026-06-19 09:12

from django.db import migrations, models


def forwards(apps, schema_editor):
    payment_model = apps.get_model('contributions', 'Payment')
    payment_model.objects.filter(status='approved').update(status='confirmed')
    for payment in payment_model.objects.filter(paid_month__isnull=True).select_related('contribution'):
        payment.paid_month = payment.contribution.month
        payment.save(update_fields=['paid_month'])


def backwards(apps, schema_editor):
    payment_model = apps.get_model('contributions', 'Payment')
    payment_model.objects.filter(status='confirmed').update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_payment_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Tasdiqlash kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20),
        ),
    ]
