# Generated by Django 5.1.15 on 2026-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0010_payment_paid_month_payment_receipt_ocr_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_day', models.PositiveSmallIntegerField(default=5)),
                ('payment_card_number', models.CharField(blank=True, max_length=40)),
                ('payment_card_holder', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badal sozlamasi',
                'verbose_name_plural': 'Badal sozlamalari',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='extracted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='extracted_card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='extracted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
