# Generated by Django 5.1.15 on 2026-06-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_drop_removed_app_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_card_seen_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
