# Generated by Django 5.1.15 on 2026-06-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_payment_card_seen_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_screenshot_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_screenshot_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
