# Generated by Django 5.1.15 on 2026-06-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_payment_screenshot_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_screenshot_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
