# Generated by Django 5.1.15 on 2026-06-17 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='duty_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='duties.dutycycle'),
        ),
        migrations.AlterUniqueTogether(
            name='dutyassignment',
            unique_together={('duty_cycle', 'month')},
        ),
    ]
