# Generated by Django 5.1.15 on 2026-06-17 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dutyassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dutyassignment',
            constraint=models.UniqueConstraint(fields=('duty_cycle', 'month'), name='unique_duty_per_month'),
        ),
    ]
